import { DatabaseSync } from 'node:sqlite'
import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'

const now=()=>new Date().toISOString()
const json=value=>JSON.stringify(value??null)
export function createDatabase(file=process.env.DATABASE_FILE||'data/khodroto.db'){
 fs.mkdirSync(path.dirname(file),{recursive:true});const db=new DatabaseSync(file);db.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;')
 db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,phone TEXT UNIQUE NOT NULL,name TEXT DEFAULT 'کاربر خودروتو',city TEXT DEFAULT '1',role TEXT DEFAULT 'user',created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS otp_codes(phone TEXT PRIMARY KEY,code_hash TEXT NOT NULL,expires_at INTEGER NOT NULL,attempts INTEGER DEFAULT 0);
 CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,user_id INTEGER NOT NULL,expires_at INTEGER NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id));
 CREATE TABLE IF NOT EXISTS listings(token TEXT PRIMARY KEY,title TEXT,city TEXT,price INTEGER,market INTEGER,score INTEGER,payload TEXT,first_seen_at TEXT,last_seen_at TEXT);
 CREATE TABLE IF NOT EXISTS price_history(id INTEGER PRIMARY KEY,token TEXT NOT NULL,price INTEGER NOT NULL,recorded_at TEXT NOT NULL,UNIQUE(token,price,recorded_at));
 CREATE TABLE IF NOT EXISTS alerts(id INTEGER PRIMARY KEY,user_id INTEGER NOT NULL,title TEXT NOT NULL,filters TEXT NOT NULL,enabled INTEGER DEFAULT 1,created_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id));
 CREATE TABLE IF NOT EXISTS saved_searches(id INTEGER PRIMARY KEY,user_id INTEGER NOT NULL,title TEXT NOT NULL,filters TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id));
 CREATE TABLE IF NOT EXISTS subscriptions(id INTEGER PRIMARY KEY,user_id INTEGER NOT NULL,plan TEXT NOT NULL,status TEXT NOT NULL,amount INTEGER NOT NULL,started_at TEXT,expires_at TEXT,created_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id));
 CREATE TABLE IF NOT EXISTS tickets(id INTEGER PRIMARY KEY,user_id INTEGER,subject TEXT NOT NULL,message TEXT NOT NULL,status TEXT DEFAULT 'open',created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS crawler_runs(id INTEGER PRIMARY KEY,source TEXT,status TEXT,items_count INTEGER DEFAULT 0,pages_count INTEGER DEFAULT 0,error TEXT,started_at TEXT,finished_at TEXT);`)
 const hash=v=>crypto.createHash('sha256').update(v).digest('hex')
 function storeListings(items=[]){const up=db.prepare(`INSERT INTO listings(token,title,city,price,market,score,payload,first_seen_at,last_seen_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(token) DO UPDATE SET title=excluded.title,city=excluded.city,price=excluded.price,market=excluded.market,score=excluded.score,payload=excluded.payload,last_seen_at=excluded.last_seen_at`),hist=db.prepare('INSERT OR IGNORE INTO price_history(token,price,recorded_at) VALUES(?,?,?)'),stamp=now();db.exec('BEGIN');try{for(const item of items){up.run(item.id,item.title,item.city,item.price,item.market,item.score,json(item),stamp,stamp);hist.run(item.id,item.price,stamp.slice(0,16))}db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}}
 function requestOtp(phone){const code=String(Math.floor(10000+Math.random()*90000));db.prepare('INSERT INTO otp_codes(phone,code_hash,expires_at,attempts) VALUES(?,?,?,0) ON CONFLICT(phone) DO UPDATE SET code_hash=excluded.code_hash,expires_at=excluded.expires_at,attempts=0').run(phone,hash(code),Date.now()+120000);return code}
 function verifyOtp(phone,code){const row=db.prepare('SELECT * FROM otp_codes WHERE phone=?').get(phone);if(!row||row.expires_at<Date.now()||row.attempts>=5)return null;if(row.code_hash!==hash(code)){db.prepare('UPDATE otp_codes SET attempts=attempts+1 WHERE phone=?').run(phone);return null}db.prepare('DELETE FROM otp_codes WHERE phone=?').run(phone);db.prepare('INSERT OR IGNORE INTO users(phone,created_at) VALUES(?,?)').run(phone,now());if(process.env.ADMIN_PHONE===phone)db.prepare("UPDATE users SET role='admin' WHERE phone=?").run(phone);const user=db.prepare('SELECT * FROM users WHERE phone=?').get(phone),token=crypto.randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)').run(hash(token),user.id,Date.now()+30*86400000,now());return{user,token}}
 function userFromToken(token){if(!token)return null;return db.prepare('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').get(hash(token),Date.now())||null}
 return{db,storeListings,requestOtp,verifyOtp,userFromToken,logout:t=>db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hash(t||'')),updateUser:(id,data)=>{db.prepare('UPDATE users SET name=?,city=? WHERE id=?').run(data.name,data.city,id);return db.prepare('SELECT * FROM users WHERE id=?').get(id)},listHistory:token=>db.prepare('SELECT price,recorded_at FROM price_history WHERE token=? ORDER BY recorded_at').all(token),stats:()=>({listings:db.prepare('SELECT COUNT(*) n FROM listings').get().n,users:db.prepare('SELECT COUNT(*) n FROM users').get().n,alerts:db.prepare('SELECT COUNT(*) n FROM alerts WHERE enabled=1').get().n,subscriptions:db.prepare("SELECT COUNT(*) n FROM subscriptions WHERE status='active'").get().n}),createAlert:(uid,b)=>db.prepare('INSERT INTO alerts(user_id,title,filters,created_at) VALUES(?,?,?,?)').run(uid,b.title,json(b.filters),now()),alerts:uid=>db.prepare('SELECT * FROM alerts WHERE user_id=? ORDER BY id DESC').all(uid),toggleAlert:(uid,id,en)=>db.prepare('UPDATE alerts SET enabled=? WHERE id=? AND user_id=?').run(en?1:0,id,uid),createTicket:(uid,b)=>db.prepare('INSERT INTO tickets(user_id,subject,message,created_at) VALUES(?,?,?,?)').run(uid,b.subject,b.message,now()),subscribe:(uid,plan,amount)=>{const start=new Date(),end=new Date(Date.now()+30*86400000);db.prepare("UPDATE subscriptions SET status='expired' WHERE user_id=? AND status='active'").run(uid);db.prepare('INSERT INTO subscriptions(user_id,plan,status,amount,started_at,expires_at,created_at) VALUES(?,?,?,?,?,?,?)').run(uid,plan,'active',amount,start.toISOString(),end.toISOString(),now());return{plan,status:'active',expiresAt:end.toISOString()}},subscription:uid=>db.prepare("SELECT * FROM subscriptions WHERE user_id=? ORDER BY id DESC LIMIT 1").get(uid)}}
