import { DatabaseSync } from 'node:sqlite'
import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'

const now=()=>new Date().toISOString()
const tehranDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tehran',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const json=value=>JSON.stringify(value??null)
export function createDatabase(file=process.env.DATABASE_FILE||'data/khodroto.db'){
 fs.mkdirSync(path.dirname(file),{recursive:true});const db=new DatabaseSync(file);db.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;')
 db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,phone TEXT UNIQUE NOT NULL,name TEXT DEFAULT 'کاربر خودروتو',city TEXT DEFAULT '1',role TEXT DEFAULT 'user',created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS otp_codes(phone TEXT PRIMARY KEY,code_hash TEXT NOT NULL,expires_at INTEGER NOT NULL,attempts INTEGER DEFAULT 0);
 CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,user_id INTEGER NOT NULL,expires_at INTEGER NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id));
 CREATE TABLE IF NOT EXISTS listings(token TEXT PRIMARY KEY,title TEXT,city TEXT,price INTEGER,market INTEGER,score INTEGER,payload TEXT,first_seen_at TEXT,last_seen_at TEXT,category TEXT DEFAULT 'light',crawl_scope TEXT DEFAULT 'web:light:1',status TEXT DEFAULT 'active',missing_count INTEGER DEFAULT 0,last_verified_at TEXT,inactive_at TEXT,removed_at TEXT);
 CREATE TABLE IF NOT EXISTS price_history(id INTEGER PRIMARY KEY,token TEXT NOT NULL,price INTEGER NOT NULL,recorded_at TEXT NOT NULL,UNIQUE(token,price,recorded_at));
 CREATE TABLE IF NOT EXISTS listing_observations(token TEXT NOT NULL,observed_date TEXT NOT NULL,category TEXT DEFAULT 'light',PRIMARY KEY(token,observed_date));
 CREATE TABLE IF NOT EXISTS alerts(id INTEGER PRIMARY KEY,user_id INTEGER NOT NULL,title TEXT NOT NULL,filters TEXT NOT NULL,enabled INTEGER DEFAULT 1,created_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id));
 CREATE TABLE IF NOT EXISTS saved_searches(id INTEGER PRIMARY KEY,user_id INTEGER NOT NULL,title TEXT NOT NULL,filters TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id));
 CREATE TABLE IF NOT EXISTS subscriptions(id INTEGER PRIMARY KEY,user_id INTEGER NOT NULL,plan TEXT NOT NULL,status TEXT NOT NULL,amount INTEGER NOT NULL,started_at TEXT,expires_at TEXT,created_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id));
 CREATE TABLE IF NOT EXISTS tickets(id INTEGER PRIMARY KEY,user_id INTEGER,subject TEXT NOT NULL,message TEXT NOT NULL,status TEXT DEFAULT 'open',created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS crawler_runs(id INTEGER PRIMARY KEY,source TEXT,status TEXT,items_count INTEGER DEFAULT 0,pages_count INTEGER DEFAULT 0,error TEXT,started_at TEXT,finished_at TEXT);
 CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS service_integrations(id INTEGER PRIMARY KEY,kind TEXT NOT NULL CHECK(kind IN ('payment','sms')),name TEXT NOT NULL,provider TEXT NOT NULL,public_config TEXT NOT NULL DEFAULT '{}',secret_enc TEXT,enabled INTEGER DEFAULT 1,priority INTEGER DEFAULT 100,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS site_slides(id INTEGER PRIMARY KEY,title TEXT NOT NULL,subtitle TEXT,badge TEXT,cta_text TEXT,cta_link TEXT,image TEXT,theme TEXT DEFAULT 'navy',enabled INTEGER DEFAULT 1,sort_order INTEGER DEFAULT 100,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS audit_logs(id INTEGER PRIMARY KEY,admin_id INTEGER,action TEXT NOT NULL,entity TEXT NOT NULL,entity_id TEXT,details TEXT,created_at TEXT NOT NULL);`)
 const listingColumns=new Set(db.prepare('PRAGMA table_info(listings)').all().map(column=>column.name));
 const listingMigrations={category:"TEXT DEFAULT 'light'",crawl_scope:"TEXT DEFAULT 'web:light:1'",status:"TEXT DEFAULT 'active'",missing_count:'INTEGER DEFAULT 0',last_verified_at:'TEXT',inactive_at:'TEXT',removed_at:'TEXT'};
 for(const [column,type] of Object.entries(listingMigrations))if(!listingColumns.has(column))db.exec(`ALTER TABLE listings ADD COLUMN ${column} ${type}`)
 db.exec("UPDATE listings SET category=COALESCE(category,'light'),crawl_scope=COALESCE(crawl_scope,'web:'||COALESCE(category,'light')||':1'),status=COALESCE(status,'active'),missing_count=COALESCE(missing_count,0)")
 const slideCount=db.prepare('SELECT COUNT(*) n FROM site_slides').get().n;if(!slideCount){const add=db.prepare('INSERT INTO site_slides(title,subtitle,badge,cta_text,cta_link,image,theme,enabled,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)'),stamp=now();add.run('بازار را با عدد ببین، نه با حدس','هزاران آگهی هر روز مقایسه می‌شوند تا قیمت واقعی و فرصت‌های قابل بررسی روشن شوند.','تحلیل هوشمند بازار','شروع جست‌وجو','/cars','/banners/market-analysis.jpg','navy',1,1,stamp,stamp);add.run('فرصت طلایی قبل از بقیه','خودروهای زیر قیمت بازار را با کنترل ریسک و دلیل شفاف پیدا کن.','فرصت‌های امروز','دیدن فرصت‌ها','/#opportunities','/banners/golden-opportunity.jpg','gold',1,2,stamp,stamp);add.run('هشدار هوشمند؛ درست در زمان مناسب','فیلترت را ذخیره کن تا فرصت تازه مطابق بودجه و مدل دلخواهت را از دست ندهی.','اعلان خودروتو','ساخت هشدار','/dashboard','/banners/smart-alerts.jpg','teal',1,3,stamp,stamp)}
 const defaults={site_name:'خودروتو',site_tagline:'ماشین خوب، قیمت درست',support_phone:'',support_email:'',free_results:'6',cache_minutes:'10',maintenance_mode:'false',card_golden:'1',card_good:'2',card_fair:'4',card_expensive:'5',card_suspicious:'6',mobile_listing_mode:'carousel',hero_ticker:'فرصت تازه پیدا شد|پژو ۲۰۷ · ۱۲٪ زیر قیمت بازار|۹۱\nیک انتخاب طلایی|دنا پلاس · ۹٪ زیر قیمت بازار|۸۷\nقیمت منصفانه پیدا شد|تارا اتوماتیک · آگهی تازه تهران|۷۹'};const settingInsert=db.prepare('INSERT OR IGNORE INTO settings(key,value,updated_at) VALUES(?,?,?)');for(const [key,value]of Object.entries(defaults))settingInsert.run(key,value,now())
 const hash=v=>crypto.createHash('sha256').update(v).digest('hex')
 const configuredCredentialKey=String(process.env.CREDENTIALS_ENCRYPTION_KEY||'')
 const credentialKey=configuredCredentialKey?crypto.createHash('sha256').update(configuredCredentialKey).digest():process.env.NODE_ENV==='production'?null:crypto.createHash('sha256').update('khodroto-development-credentials-key').digest()
 function encryptSecret(value){if(!value)return null;if(!credentialKey){const error=new Error('CREDENTIALS_ENCRYPTION_KEY is required');error.code='ENCRYPTION_KEY_REQUIRED';throw error}const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',credentialKey,iv),encrypted=Buffer.concat([cipher.update(String(value),'utf8'),cipher.final()]);return [iv.toString('base64url'),cipher.getAuthTag().toString('base64url'),encrypted.toString('base64url')].join('.')}
 function decryptSecret(value){if(!value||!credentialKey)return'';try{const[iv,tag,data]=String(value).split('.'),decipher=crypto.createDecipheriv('aes-256-gcm',credentialKey,Buffer.from(iv,'base64url'));decipher.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([decipher.update(Buffer.from(data,'base64url')),decipher.final()]).toString('utf8')}catch{return''}}
 const parseConfig=value=>{try{return JSON.parse(value||'{}')}catch{return{}}}
 function integrations(kind){return db.prepare('SELECT id,kind,name,provider,public_config,secret_enc,enabled,priority,created_at,updated_at FROM service_integrations WHERE kind=? ORDER BY enabled DESC,priority ASC,id DESC').all(kind).map(row=>({...row,config:parseConfig(row.public_config),enabled:Boolean(row.enabled),hasSecret:Boolean(row.secret_enc),secret_enc:undefined}))}
 function saveIntegration(kind,data,id=null){if(!['payment','sms'].includes(kind))throw new Error('INVALID_KIND');const stamp=now(),name=String(data.name||'').trim().slice(0,80),provider=String(data.provider||'custom').trim().slice(0,50),config=json(data.config||{}),enabled=data.enabled===false?0:1,priority=Math.max(0,Math.min(9999,Number.isFinite(Number(data.priority))?Number(data.priority):100));if(name.length<2)throw new Error('INVALID_NAME');if(id){const current=db.prepare('SELECT secret_enc FROM service_integrations WHERE id=? AND kind=?').get(id,kind);if(!current)return null;const secret=data.secret?encryptSecret(String(data.secret).slice(0,4000)):current.secret_enc;db.prepare('UPDATE service_integrations SET name=?,provider=?,public_config=?,secret_enc=?,enabled=?,priority=?,updated_at=? WHERE id=? AND kind=?').run(name,provider,config,secret,enabled,priority,stamp,id,kind)}else{db.prepare('INSERT INTO service_integrations(kind,name,provider,public_config,secret_enc,enabled,priority,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(kind,name,provider,config,encryptSecret(String(data.secret||'').slice(0,4000)),enabled,priority,stamp,stamp)}return integrations(kind)}
 function deleteIntegration(kind,id){return db.prepare('DELETE FROM service_integrations WHERE id=? AND kind=?').run(id,kind)}
 function activeIntegrations(kind){return db.prepare('SELECT id,name,provider,public_config,secret_enc,priority FROM service_integrations WHERE kind=? AND enabled=1 ORDER BY priority ASC,id ASC').all(kind).map(row=>({...row,config:parseConfig(row.public_config),secret:decryptSecret(row.secret_enc),public_config:undefined,secret_enc:undefined}))}
 function storeCrawl(result={},options={}){
  const items=Array.isArray(result.items)?result.items:[],category=String(options.category||result.category||'light'),scope=String(options.scope||result.scope||`web:${category}:1`),stamp=now()
  const observed=[...new Set((result.observedTokens||items.map(item=>item.id)).filter(Boolean).map(String))]
  const up=db.prepare(`INSERT INTO listings(token,title,city,price,market,score,payload,first_seen_at,last_seen_at,category,crawl_scope,status,missing_count,last_verified_at,inactive_at,removed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,'active',0,?,NULL,NULL) ON CONFLICT(token) DO UPDATE SET title=excluded.title,city=excluded.city,price=excluded.price,market=excluded.market,score=excluded.score,payload=excluded.payload,last_seen_at=excluded.last_seen_at,category=excluded.category,crawl_scope=excluded.crawl_scope,status='active',missing_count=0,last_verified_at=excluded.last_verified_at,inactive_at=NULL,removed_at=NULL`)
  const hist=db.prepare('INSERT OR IGNORE INTO price_history(token,price,recorded_at) VALUES(?,?,?)')
  db.exec('CREATE TEMP TABLE IF NOT EXISTS crawl_seen_tokens(token TEXT PRIMARY KEY)')
  const seen=db.prepare('INSERT OR IGNORE INTO crawl_seen_tokens(token) VALUES(?)')
  const observation=db.prepare('INSERT OR IGNORE INTO listing_observations(token,observed_date,category) VALUES(?,?,?)')
  db.exec('BEGIN')
  try{
   db.exec('CREATE TEMP TABLE IF NOT EXISTS crawl_seen_tokens(token TEXT PRIMARY KEY);DELETE FROM crawl_seen_tokens;')
   for(const token of observed){seen.run(token);observation.run(token,tehranDate(),category)}
   for(const item of items){if(!item?.id)continue;up.run(item.id,item.title,item.city,item.price,item.market,item.score,json(item),stamp,stamp,category,scope,stamp);hist.run(item.id,item.price,stamp.slice(0,16))}
   db.prepare(`UPDATE listings SET last_seen_at=?,last_verified_at=?,missing_count=0,status='active',inactive_at=NULL,removed_at=NULL WHERE token IN (SELECT token FROM crawl_seen_tokens)`).run(stamp,stamp)
   if(options.reconcile){
    db.prepare(`UPDATE listings SET missing_count=missing_count+1,status=CASE WHEN missing_count+1>=3 THEN 'inactive' ELSE 'stale' END,inactive_at=CASE WHEN missing_count+1>=3 THEN COALESCE(inactive_at,?) ELSE inactive_at END WHERE crawl_scope=? AND status!='removed' AND token NOT IN (SELECT token FROM crawl_seen_tokens)`).run(stamp,scope)
   }
   db.exec('COMMIT')
  }catch(e){db.exec('ROLLBACK');throw e}
  return{stored:items.length,observed:observed.length,reconciled:Boolean(options.reconcile)}
 }
 function storeListings(items=[]){return storeCrawl({items},{reconcile:false})}
 function verificationCandidates(category='light',limit=25){return db.prepare(`SELECT token,status,missing_count FROM listings WHERE category=? AND status IN ('stale','inactive') ORDER BY missing_count DESC,last_seen_at ASC LIMIT ?`).all(category,limit)}
 function markListingVerification(token,state){const stamp=now();if(state==='removed')return db.prepare(`UPDATE listings SET status='removed',removed_at=COALESCE(removed_at,?),last_verified_at=? WHERE token=?`).run(stamp,stamp,token);if(state==='active')return db.prepare(`UPDATE listings SET status='active',missing_count=0,last_seen_at=?,last_verified_at=?,inactive_at=NULL,removed_at=NULL WHERE token=?`).run(stamp,stamp,token)}
 function publicStats(){
  const today=tehranDate()
  return{
   analyzedToday:db.prepare('SELECT COUNT(*) n FROM listing_observations WHERE observed_date=?').get(today).n,
   totalListings:db.prepare('SELECT COUNT(*) n FROM listings').get().n,
   goldenOpportunities:db.prepare("SELECT COUNT(*) n FROM listings WHERE status='active' AND score>=85").get().n,
   activeListings:db.prepare("SELECT COUNT(*) n FROM listings WHERE status='active'").get().n,
   date:today,
  }
 }
 function slides(activeOnly=false){return db.prepare(`SELECT * FROM site_slides ${activeOnly?'WHERE enabled=1':''} ORDER BY sort_order ASC,id ASC`).all().map(row=>({...row,enabled:Boolean(row.enabled)}))}
 function saveSlide(data,id=null){const stamp=now(),values=[String(data.title||'').trim().slice(0,150),String(data.subtitle||'').trim().slice(0,500),String(data.badge||'').trim().slice(0,80),String(data.cta_text||'').trim().slice(0,80),String(data.cta_link||'/cars').trim().slice(0,500),String(data.image||'').trim().slice(0,500),['navy','gold','teal','coral'].includes(data.theme)?data.theme:'navy',data.enabled===false?0:1,Math.max(0,Number.isFinite(Number(data.sort_order))?Number(data.sort_order):100)];if(values[0].length<2)throw new Error('INVALID_TITLE');if(id){db.prepare('UPDATE site_slides SET title=?,subtitle=?,badge=?,cta_text=?,cta_link=?,image=?,theme=?,enabled=?,sort_order=?,updated_at=? WHERE id=?').run(...values,stamp,id)}else db.prepare('INSERT INTO site_slides(title,subtitle,badge,cta_text,cta_link,image,theme,enabled,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(...values,stamp,stamp);return slides()}
 function deleteSlide(id){return db.prepare('DELETE FROM site_slides WHERE id=?').run(id)}
 function audit(adminId,action,entity,entityId='',details={}){db.prepare('INSERT INTO audit_logs(admin_id,action,entity,entity_id,details,created_at) VALUES(?,?,?,?,?,?)').run(adminId||null,String(action).slice(0,80),String(entity).slice(0,80),String(entityId).slice(0,100),json(details),now())}
 function audits(){return db.prepare('SELECT a.*,u.name admin_name,u.phone admin_phone FROM audit_logs a LEFT JOIN users u ON u.id=a.admin_id ORDER BY a.id DESC LIMIT 250').all()}
 function requestOtp(phone){const code=String(Math.floor(10000+Math.random()*90000));db.prepare('INSERT INTO otp_codes(phone,code_hash,expires_at,attempts) VALUES(?,?,?,0) ON CONFLICT(phone) DO UPDATE SET code_hash=excluded.code_hash,expires_at=excluded.expires_at,attempts=0').run(phone,hash(code),Date.now()+120000);return code}
 function verifyOtp(phone,code){const row=db.prepare('SELECT * FROM otp_codes WHERE phone=?').get(phone);if(!row||row.expires_at<Date.now()||row.attempts>=5)return null;if(row.code_hash!==hash(code)){db.prepare('UPDATE otp_codes SET attempts=attempts+1 WHERE phone=?').run(phone);return null}db.prepare('DELETE FROM otp_codes WHERE phone=?').run(phone);db.prepare('INSERT OR IGNORE INTO users(phone,created_at) VALUES(?,?)').run(phone,now());if(process.env.ADMIN_PHONE===phone||process.env.NODE_ENV!=='production')db.prepare("UPDATE users SET role='admin' WHERE phone=?").run(phone);const user=db.prepare('SELECT * FROM users WHERE phone=?').get(phone),token=crypto.randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)').run(hash(token),user.id,Date.now()+30*86400000,now());return{user,token}}
 function userFromToken(token){if(!token)return null;return db.prepare('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').get(hash(token),Date.now())||null}
 function createAdminSession(phone){const normalized=String(phone||process.env.ADMIN_PHONE||'').trim();if(!/^09\d{9}$/.test(normalized))return null;db.prepare('INSERT OR IGNORE INTO users(phone,created_at) VALUES(?,?)').run(normalized,now());db.prepare("UPDATE users SET role='admin' WHERE phone=?").run(normalized);const user=db.prepare('SELECT * FROM users WHERE phone=?').get(normalized),token=crypto.randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)').run(hash(token),user.id,Date.now()+12*60*60*1000,now());return{user,token}}
 return{db,storeListings,storeCrawl,verificationCandidates,markListingVerification,publicStats,integrations,saveIntegration,deleteIntegration,activeIntegrations,slides,saveSlide,deleteSlide,audit,audits,requestOtp,verifyOtp,userFromToken,createAdminSession,
 logout:t=>db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hash(t||'')),
 updateUser:(id,data)=>{db.prepare('UPDATE users SET name=?,city=? WHERE id=?').run(data.name,data.city,id);return db.prepare('SELECT * FROM users WHERE id=?').get(id)},
 listHistory:token=>db.prepare('SELECT price,recorded_at FROM price_history WHERE token=? ORDER BY recorded_at').all(token),
 stats:()=>({listings:db.prepare('SELECT COUNT(*) n FROM listings').get().n,activeListings:db.prepare("SELECT COUNT(*) n FROM listings WHERE status='active'").get().n,staleListings:db.prepare("SELECT COUNT(*) n FROM listings WHERE status='stale'").get().n,inactiveListings:db.prepare("SELECT COUNT(*) n FROM listings WHERE status='inactive'").get().n,removedListings:db.prepare("SELECT COUNT(*) n FROM listings WHERE status='removed'").get().n,users:db.prepare('SELECT COUNT(*) n FROM users').get().n,alerts:db.prepare('SELECT COUNT(*) n FROM alerts WHERE enabled=1').get().n,subscriptions:db.prepare("SELECT COUNT(*) n FROM subscriptions WHERE status='active'").get().n,tickets:db.prepare("SELECT COUNT(*) n FROM tickets WHERE status='open'").get().n,paymentGateways:db.prepare("SELECT COUNT(*) n FROM service_integrations WHERE kind='payment' AND enabled=1").get().n,smsProviders:db.prepare("SELECT COUNT(*) n FROM service_integrations WHERE kind='sms' AND enabled=1").get().n,activeSlides:db.prepare('SELECT COUNT(*) n FROM site_slides WHERE enabled=1').get().n,analyzedToday:db.prepare('SELECT COUNT(*) n FROM listing_observations WHERE observed_date=?').get(tehranDate()).n,goldenOpportunities:db.prepare("SELECT COUNT(*) n FROM listings WHERE status='active' AND score>=85").get().n}),
 createAlert:(uid,b)=>db.prepare('INSERT INTO alerts(user_id,title,filters,created_at) VALUES(?,?,?,?)').run(uid,b.title,json(b.filters),now()),alerts:uid=>db.prepare('SELECT * FROM alerts WHERE user_id=? ORDER BY id DESC').all(uid),toggleAlert:(uid,id,en)=>db.prepare('UPDATE alerts SET enabled=? WHERE id=? AND user_id=?').run(en?1:0,id,uid),
 createTicket:(uid,b)=>db.prepare('INSERT INTO tickets(user_id,subject,message,created_at) VALUES(?,?,?,?)').run(uid,b.subject,b.message,now()),
 subscribe:(uid,plan,amount)=>{const start=new Date(),end=new Date(Date.now()+30*86400000);db.prepare("UPDATE subscriptions SET status='expired' WHERE user_id=? AND status='active'").run(uid);db.prepare('INSERT INTO subscriptions(user_id,plan,status,amount,started_at,expires_at,created_at) VALUES(?,?,?,?,?,?,?)').run(uid,plan,'active',amount,start.toISOString(),end.toISOString(),now());return{plan,status:'active',expiresAt:end.toISOString()}},subscription:uid=>db.prepare("SELECT * FROM subscriptions WHERE user_id=? ORDER BY id DESC LIMIT 1").get(uid),
 adminUsers:()=>db.prepare(`SELECT u.id,u.phone,u.name,u.city,u.role,u.created_at,(SELECT plan FROM subscriptions s WHERE s.user_id=u.id AND s.status='active' ORDER BY id DESC LIMIT 1) plan FROM users u ORDER BY u.id DESC LIMIT 200`).all(),
 adminSubscriptions:()=>db.prepare('SELECT s.*,u.phone,u.name FROM subscriptions s JOIN users u ON u.id=s.user_id ORDER BY s.id DESC LIMIT 200').all(),
 adminTickets:()=>db.prepare('SELECT t.*,u.phone,u.name FROM tickets t LEFT JOIN users u ON u.id=t.user_id ORDER BY t.id DESC LIMIT 200').all(),
 adminListings:()=>db.prepare('SELECT token,title,city,price,score,category,crawl_scope,status,missing_count,first_seen_at,last_seen_at,last_verified_at,inactive_at,removed_at FROM listings ORDER BY last_seen_at DESC LIMIT 200').all(),
 setUserRole:(id,role)=>db.prepare('UPDATE users SET role=? WHERE id=?').run(role,id),
 setTicketStatus:(id,status)=>db.prepare('UPDATE tickets SET status=? WHERE id=?').run(status,id),
 setSubscriptionStatus:(id,status)=>db.prepare('UPDATE subscriptions SET status=? WHERE id=?').run(status,id),
 setListingStatus:(token,status)=>db.prepare("UPDATE listings SET status=?,inactive_at=CASE WHEN ?='inactive' THEN COALESCE(inactive_at,?) ELSE inactive_at END,removed_at=CASE WHEN ?='removed' THEN COALESCE(removed_at,?) ELSE removed_at END WHERE token=?").run(status,status,now(),status,now(),token),
 settings:()=>Object.fromEntries(db.prepare('SELECT key,value FROM settings').all().map(x=>[x.key,x.value])),
 updateSettings:values=>{const q=db.prepare('INSERT INTO settings(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at');for(const[key,value]of Object.entries(values))if(Object.hasOwn(defaults,key))q.run(key,String(value).slice(0,500),now());return Object.fromEntries(db.prepare('SELECT key,value FROM settings').all().map(x=>[x.key,x.value]))}
}}
