import React,{useEffect,useState}from'react'
import{ChevronDown,CreditCard,MessageSquareText,Plus,Save,ShieldCheck,Trash2}from'lucide-react'

const providers={payment:[['zarinpal','زرین‌پال'],['idpay','آیدی‌پی'],['nextpay','نکست‌پی'],['behpardakht','به‌پرداخت ملت'],['sep','پرداخت الکترونیک سامان'],['saman','بانک سامان'],['custom','درگاه سفارشی']],sms:[['kavenegar','کاوه‌نگار'],['melipayamak','ملی پیامک'],['farazsms','فراز اس‌ام‌اس'],['smsir','SMS.ir'],['ippanel','IPPanel'],['custom','پنل سفارشی']]}
const empty=kind=>({name:'',provider:providers[kind][0][0],secret:'',enabled:true,priority:100,config:kind==='payment'?{merchantId:'',callbackUrl:'',endpoint:''}:{sender:'',templateId:'',endpoint:''}})

async function request(url,options){const response=await fetch(url,options),data=await response.json();if(!response.ok)throw Error(data.error||'REQUEST_FAILED');return data}

function Editor({kind,item,onDone,onCancel}){
 const[draft,setDraft]=useState(item?{...item,secret:'',config:{...item.config}}:empty(kind)),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 useEffect(()=>setDraft(item?{...item,secret:'',config:{...item.config}}:empty(kind)),[item,kind])
 const set=(key,value)=>setDraft({...draft,[key]:value}),setConfig=(key,value)=>setDraft({...draft,config:{...draft.config,[key]:value}})
 async function save(event){event.preventDefault();setBusy(true);setMessage('');try{const url=item?`/api/admin/integrations/${kind}/${item.id}`:`/api/admin/integrations/${kind}`,method=item?'PATCH':'POST';await request(url,{method,headers:{'content-type':'application/json'},body:JSON.stringify(draft)});setMessage('ذخیره شد');onDone()}catch(error){setMessage(error.message==='ENCRYPTION_KEY_REQUIRED'?'کلید رمزنگاری اطلاعات محرمانه روی سرور تنظیم نشده است.':'ذخیره انجام نشد؛ فیلدها را بررسی کنید.')}finally{setBusy(false)}}
 return <form className="integration-editor" onSubmit={save}><div className="integration-fields"><label>نام نمایشی<input required minLength="2" value={draft.name} onChange={e=>set('name',e.target.value)} placeholder={kind==='payment'?'مثلاً زرین‌پال اصلی':'مثلاً پیامک تراکنشی'}/></label><label>ارائه‌دهنده<div className="admin-select"><select value={draft.provider} onChange={e=>set('provider',e.target.value)}>{providers[kind].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><ChevronDown/></div></label><label>{kind==='payment'?'کلید API / رمز پذیرنده':'کلید API پنل'}<input type="password" value={draft.secret} onChange={e=>set('secret',e.target.value)} placeholder={item?.hasSecret?'برای حفظ کلید قبلی خالی بگذارید':'اطلاعات محرمانه'}/></label><label>اولویت<input type="number" min="0" max="9999" value={draft.priority} onChange={e=>set('priority',e.target.value)}/></label>{kind==='payment'?<><label>شناسه پذیرنده<input value={draft.config.merchantId||''} onChange={e=>setConfig('merchantId',e.target.value)} placeholder="Merchant ID"/></label><label>آدرس بازگشت<input dir="ltr" value={draft.config.callbackUrl||''} onChange={e=>setConfig('callbackUrl',e.target.value)} placeholder="https://example.com/payment/callback"/></label></>:<><label>شماره/خط ارسال<input value={draft.config.sender||''} onChange={e=>setConfig('sender',e.target.value)} placeholder="خط خدماتی"/></label><label>شناسه الگوی OTP<input value={draft.config.templateId||''} onChange={e=>setConfig('templateId',e.target.value)} placeholder="Template ID"/></label></>}<label className="wide">نشانی API سفارشی <span>اختیاری</span><input dir="ltr" value={draft.config.endpoint||''} onChange={e=>setConfig('endpoint',e.target.value)} placeholder="https://api.provider.example/v1"/></label></div><label className="integration-enabled"><input type="checkbox" checked={draft.enabled} onChange={e=>set('enabled',e.target.checked)}/> این اتصال فعال باشد</label><div className="integration-actions"><button className="primary" disabled={busy} type="submit"><Save/>{busy?'در حال ذخیره…':'ذخیره اتصال'}</button>{onCancel&&<button className="secondary" type="button" onClick={onCancel}>انصراف</button>}{message&&<small>{message}</small>}</div></form>
}

function IntegrationCard({kind,item,reload}){const[editing,setEditing]=useState(false),[busy,setBusy]=useState(false);async function toggle(){setBusy(true);try{await request(`/api/admin/integrations/${kind}/${item.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({...item,enabled:!item.enabled})});reload()}finally{setBusy(false)}}async function remove(){if(!window.confirm(`اتصال «${item.name}» حذف شود؟`))return;setBusy(true);try{await request(`/api/admin/integrations/${kind}/${item.id}`,{method:'DELETE'});reload()}finally{setBusy(false)}}return <article className={'integration-card '+(item.enabled?'active':'')}><header><div className="integration-icon">{kind==='payment'?<CreditCard/>:<MessageSquareText/>}</div><div><b>{item.name}</b><span>{providers[kind].find(x=>x[0]===item.provider)?.[1]||item.provider}</span></div><span className="integration-state">{item.enabled?'فعال':'غیرفعال'}</span></header><div className="integration-meta"><span>اولویت <b>{item.priority}</b></span><span>کلید محرمانه <b>{item.hasSecret?'ثبت شده':'ثبت نشده'}</b></span>{kind==='payment'&&item.config?.merchantId&&<span>پذیرنده <b>{item.config.merchantId}</b></span>}{kind==='sms'&&item.config?.sender&&<span>خط ارسال <b>{item.config.sender}</b></span>}</div>{editing&&<Editor kind={kind} item={item} onDone={()=>{setEditing(false);reload()}} onCancel={()=>setEditing(false)}/>}<footer><button disabled={busy} onClick={toggle}>{item.enabled?'غیرفعال‌کردن':'فعال‌کردن'}</button><button onClick={()=>setEditing(!editing)}>ویرایش</button><button className="danger" disabled={busy} onClick={remove}><Trash2/> حذف</button></footer></article>}

function IntegrationSection({kind,items,reload}){const[adding,setAdding]=useState(false),Icon=kind==='payment'?CreditCard:MessageSquareText,title=kind==='payment'?'درگاه‌های پرداخت':'پنل‌های پیامکی',description=kind==='payment'?'چند درگاه را هم‌زمان فعال کنید؛ اولویت کمتر زودتر در مسیر پرداخت پیشنهاد می‌شود.':'چند پنل را هم‌زمان برای افزونگی و تفکیک پیام‌های تراکنشی آماده نگه دارید.';return <section className="dash-section integration-section"><div className="dash-section-head"><div><h2><Icon/> {title}</h2><p>{description}</p></div><button className="secondary" onClick={()=>setAdding(!adding)}><Plus/> افزودن اتصال</button></div>{adding&&<Editor kind={kind} onDone={()=>{setAdding(false);reload()}} onCancel={()=>setAdding(false)}/>}<div className="integration-list">{items.length?items.map(item=><IntegrationCard key={item.id} kind={kind} item={item} reload={reload}/>):<div className="integration-empty"><ShieldCheck/><b>هنوز اتصالی ثبت نشده است.</b><span>با افزودن اولین {kind==='payment'?'درگاه':'پنل'}، تنظیمات محرمانه به‌صورت رمز‌شده ذخیره می‌شود.</span></div>}</div></section>}

export function IntegrationsManager({value,reload}){return <div className="integrations-manager"><div className="credentials-notice"><ShieldCheck/><div><b>نگهداری امن اطلاعات اتصال</b><span>کلیدهای محرمانه در API مدیریت بازگردانده نمی‌شوند و در دیتابیس با AES-256-GCM رمز می‌شوند. در production متغیر CREDENTIALS_ENCRYPTION_KEY الزامی است.</span></div></div><IntegrationSection kind="payment" items={value.payment||[]} reload={reload}/><IntegrationSection kind="sms" items={value.sms||[]} reload={reload}/></div>}
