import React,{useEffect,useState}from'react'
import{IntegrationsManager}from'./admin-integrations'
import{Activity,AlertTriangle,Bell,Car,Database,RefreshCw,Save,Settings,ShieldCheck,TicketCheck,Users,WalletCards}from'lucide-react'
const n=x=>new Intl.NumberFormat('fa-IR').format(x||0)
const money=x=>`${n(Math.round((x||0)/1e6))} م.ت`
const listingStatus={active:'فعال',stale:'در انتظار بررسی',inactive:'غیرفعال',removed:'حذف‌شده'}
export function AdminPage(){
 const[tab,setTab]=useState('overview'),[stats,setStats]=useState(null),[status,setStatus]=useState(null),[data,setData]=useState([]),[settings,setSettings]=useState({}),[integrations,setIntegrations]=useState({payment:[],sms:[]}),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function api(url,options){const r=await fetch(url,options);if(r.status===401||r.status===403){setError(r.status===401?'برای مشاهده پنل ابتدا با شماره مدیر وارد شوید.':'این حساب دسترسی مدیریت ندارد.');throw Error()}return r.json()}
 async function load(next=tab){setBusy(true);setError('');try{const[s,i]=await Promise.all([api('/api/admin/stats'),fetch('/api/integration/status').then(r=>r.json())]);setStats(s);setStatus(i);if(next==='users')setData((await api('/api/admin/users')).items);if(next==='subscriptions')setData((await api('/api/admin/subscriptions')).items);if(next==='tickets')setData((await api('/api/admin/tickets')).items);if(next==='listings')setData((await api('/api/admin/listings')).items);if(next==='settings'){const[general,payment,sms]=await Promise.all([api('/api/admin/settings'),api('/api/admin/integrations/payment'),api('/api/admin/integrations/sms')]);setSettings(general.settings);setIntegrations({payment:payment.items,sms:sms.items})}}catch{}finally{setBusy(false)}}
 useEffect(()=>{load(tab)},[tab])
 async function patch(url,body){await api(url,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)});load(tab)}
 const tabs=[['overview','نمای کلی',Activity],['users','کاربران',Users],['subscriptions','اشتراک‌ها',WalletCards],['tickets','تیکت‌ها',TicketCheck],['listings','آگهی‌ها',Car],['settings','تنظیمات',Settings]]
 return <main className="dashboard-page"><div className="wrap admin"><div className="admin-head"><div><span>مرکز عملیات خودروتو</span><h1>مدیریت پلتفرم</h1></div><div className="admin-actions"><a href="/">مشاهده سایت</a><button className="secondary" onClick={()=>load(tab)}><RefreshCw className={busy?'spin':''}/> به‌روزرسانی</button></div></div>{error?<div className="admin-denied"><ShieldCheck/><h2>دسترسی محدود</h2><p>{error}</p><a className="primary" href="/">بازگشت و ورود</a></div>:<><nav className="admin-tabs">{tabs.map(([id,label,Icon])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon/>{label}</button>)}</nav>{tab==='overview'&&<Overview stats={stats} status={status} refresh={async()=>{setBusy(true);try{await api('/api/admin/crawler/refresh',{method:'POST'})}finally{setBusy(false);load()}}}/>} {tab==='users'&&<Table headers={['کاربر','موبایل','شهر','پلن','نقش','عملیات']} rows={data.map(x=>[x.name,x.phone,x.city,x.plan||'رایگان',x.role,<button onClick={()=>patch(`/api/admin/users/${x.id}`,{role:x.role==='admin'?'user':'admin'})}>{x.role==='admin'?'کاربر عادی':'مدیر شود'}</button>])}/>} {tab==='subscriptions'&&<Table headers={['کاربر','پلن','مبلغ','وضعیت','شروع','انقضا']} rows={data.map(x=>[x.name||x.phone,x.plan,n(x.amount),x.status,new Date(x.started_at).toLocaleDateString('fa-IR'),new Date(x.expires_at).toLocaleDateString('fa-IR')])}/>} {tab==='tickets'&&<Table headers={['کاربر','موضوع','پیام','وضعیت','تاریخ','عملیات']} rows={data.map(x=>[x.name||x.phone||'مهمان',x.subject,x.message,x.status,new Date(x.created_at).toLocaleDateString('fa-IR'),<select value={x.status} onChange={e=>patch(`/api/admin/tickets/${x.id}`,{status:e.target.value})}><option value="open">باز</option><option value="pending">در حال بررسی</option><option value="closed">بسته</option></select>])}/>} {tab==='listings'&&<Table headers={['عنوان','شهر','قیمت','امتیاز','وضعیت','عدم مشاهده','آخرین مشاهده','لینک']} rows={data.map(x=>[x.title,x.city,money(x.price),n(x.score),<span className={`listing-status ${x.status}`}>{listingStatus[x.status]||x.status}</span>,n(x.missing_count),new Date(x.last_seen_at).toLocaleString('fa-IR'),<a target="_blank" rel="noreferrer" href={`https://divar.ir/v/${x.token}`}>دیوار ↗</a>])}/>} {tab==='settings'&&<><SettingsForm value={settings} setValue={setSettings} save={()=>patch('/api/admin/settings',settings)}/><IntegrationsManager value={integrations} reload={()=>load('settings')}/></>}</>}</div></main>
}
function Overview({stats,status,refresh}){return <><div className="dash-stats">{[[Car,'آگهی‌ها',stats?.listings],[Users,'کاربران',stats?.users],[Bell,'هشدار فعال',stats?.alerts],[WalletCards,'اشتراک فعال',stats?.subscriptions]].map(([I,l,v])=><article key={l}><I/><span><b>{n(v)}</b><small>{l}</small></span></article>)}</div><section className="dash-section"><div className="dash-section-head"><h2>سلامت جمع‌آوری داده</h2><p>وضعیت اتصال، کش و پردازش پس‌زمینه</p></div><div className="health-grid"><Health icon={Activity} value={status?.configured?'فعال':'قطع'} label="اتصال"/><Health icon={Database} value={n(stats?.activeListings)} label="آگهی فعال"/><Health icon={AlertTriangle} value={n((stats?.inactiveListings||0)+(stats?.removedListings||0))} label="خارج‌شده"/><Health icon={WalletCards} value={n(stats?.paymentGateways)} label="درگاه فعال"/><Health icon={Bell} value={n(stats?.smsProviders)} label="پنل پیامک فعال"/><Health icon={Database} value={n(status?.cachedSearches)} label="کش"/><Health icon={RefreshCw} value={status?.refreshing?'در حال اجرا':'آماده'} label="Worker"/><Health icon={AlertTriangle} value={status?.provider||'—'} label="منبع"/></div><button className="primary admin-crawl" onClick={refresh}><RefreshCw/> جمع‌آوری همین حالا</button></section></>}
function Health({icon:Icon,value,label}){return <div><Icon/><span><b>{value}</b><small>{label}</small></span></div>}
function Table({headers,rows}){return <section className="admin-table-wrap"><table className="admin-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>):<tr><td colSpan={headers.length}>هنوز داده‌ای ثبت نشده است.</td></tr>}</tbody></table></section>}
function SettingsForm({value,setValue,save}){const fields=[['site_name','نام سایت'],['site_tagline','شعار سایت'],['support_phone','شماره پشتیبانی'],['support_email','ایمیل پشتیبانی'],['free_results','تعداد نتایج رایگان'],['cache_minutes','زمان کش (دقیقه)']];return <section className="dash-section"><div className="dash-section-head"><h2>تنظیمات عمومی</h2><p>مشخصات نمایش و تنظیمات پایه پلتفرم</p></div><div className="admin-settings">{fields.map(([key,label])=><label key={key}>{label}<input value={value[key]||''} onChange={e=>setValue({...value,[key]:e.target.value})}/></label>)}<label className="maintenance"><input type="checkbox" checked={value.maintenance_mode==='true'} onChange={e=>setValue({...value,maintenance_mode:String(e.target.checked)})}/> حالت تعمیر و نگهداری</label><button className="primary" onClick={save}><Save/> ذخیره تنظیمات</button></div></section>}
