import React,{useEffect,useMemo,useState}from'react'
import{ArrowLeft,BarChart3,Car,Download,Plus,RefreshCw,Target,Trash2,TrendingUp,UserRound,Users,WalletCards,X}from'lucide-react'

const n=value=>new Intl.NumberFormat('fa-IR').format(value||0)
const money=value=>`${n(Math.round(Number(value)||0))} تومان`
const date=value=>value?new Date(value).toLocaleString('fa-IR'):'—'
const toInputDateTime=value=>{if(!value)return'';const d=new Date(value);if(!Number.isFinite(d.getTime()))return String(value).slice(0,16);const pad=x=>String(x).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
const inventoryStatus={available:'آماده فروش',reserved:'رزرو شده',sold:'فروخته شد',repair:'آماده‌سازی'}
const leadStatus={new:'جدید',contacted:'تماس گرفته شد',negotiating:'مذاکره',won:'فروش موفق',lost:'از دست رفته'}
const leadPriority={cold:'سرد',normal:'معمولی',hot:'داغ'}
const inventoryBlank={title:'',brand:'',model:'',year:'',buy_price:'',target_price:'',sale_price:'',sold_at:'',status:'available',notes:''}
const leadBlank={name:'',phone:'',vehicle:'',budget:'',status:'new',source:'',priority:'normal',next_follow_at:'',last_contact_at:'',notes:'',inventory_id:''}

async function request(url,options){const response=await fetch(url,options),body=response.headers.get('content-type')?.includes('json')?await response.json():null;if(!response.ok)throw Error(body?.error||'REQUEST_FAILED');return body}
const field=(value,setValue,key)=>(event=>setValue({...value,[key]:event.target.value}))

export function DealerPage({onToast}){
 const[data,setData]=useState(null),[tab,setTab]=useState('overview'),[error,setError]=useState(''),[busy,setBusy]=useState(true),[inventoryForm,setInventoryForm]=useState(null),[leadForm,setLeadForm]=useState(null)
 async function load(){setBusy(true);try{setData(await request('/api/dealer/summary'));setError('')}catch(error){setError(error.message)}finally{setBusy(false)}}
 useEffect(()=>{load()},[])
 async function saveInventory(event){event.preventDefault();const item=inventoryForm,editing=Boolean(item.id);await request(editing?`/api/dealer/inventory/${item.id}`:'/api/dealer/inventory',{method:editing?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(item)});setInventoryForm(null);onToast?.('موجودی نمایشگاه ذخیره شد.');load()}
 async function saveLead(event){event.preventDefault();const item=leadForm,editing=Boolean(item.id);await request(editing?`/api/dealer/leads/${item.id}`:'/api/dealer/leads',{method:editing?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(item)});setLeadForm(null);onToast?.('اطلاعات مشتری و پیگیری ذخیره شد.');load()}
 async function quickContact(lead){const next=new Date(Date.now()+2*86400000).toISOString();await request(`/api/dealer/leads/${lead.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({...lead,status:lead.status==='new'?'contacted':lead.status,last_contact_at:new Date().toISOString(),next_follow_at:next})});onToast?.('تماس ثبت شد و پیگیری بعدی برای دو روز دیگر تنظیم شد.');load()}
 async function remove(type,id){if(!window.confirm('این رکورد حذف شود؟'))return;await request(`/api/dealer/${type}/${id}`,{method:'DELETE'});load()}
 if(busy&&!data)return <main className="dealer-page"><div className="dealer-loading"><RefreshCw className="spin"/> در حال آماده‌سازی پنل نمایشگاه…</div></main>
 if(error)return <main className="dealer-page"><div className="dealer-locked"><Car/><span>ابزارهای واقعی نمایشگاه</span><h1>{error==='AUTH_REQUIRED'?'برای ورود به پنل نمایشگاه وارد حساب شوید.':'این بخش مخصوص اشتراک فعال نمایشگاه حرفه‌ای است.'}</h1><p>مدیریت موجودی، مشتریان، سود هدف، گزارش بازار، پیگیری فروش و خروجی اطلاعات پس از فعال‌شدن پلن نمایشگاه در دسترس قرار می‌گیرد.</p><div><a className="primary" href={error==='AUTH_REQUIRED'?'/?login=1':'/pricing'}>{error==='AUTH_REQUIRED'?'ورود به حساب':'مشاهده پلن نمایشگاه'}</a><a className="secondary" href="/">بازگشت به سایت</a></div></div></main>
 const metrics=data?.metrics||{}
 const followups=data?.followups||[]
 return <main className="dealer-page"><header className="dealer-header"><div className="wrap"><a href="/" className="dealer-brand"><img src="/brand/khodroto-mark.svg"/><span><b>خودروتو نمایشگاه</b><small>مرکز عملیات فروش حرفه‌ای</small></span></a><nav>{[['overview','نمای کلی',BarChart3],['inventory','موجودی خودرو',Car],['leads','مشتریان و فروش',Users],['followups','پیگیری‌ها',RefreshCw]].map(([id,label,Icon])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon/>{label}</button>)}</nav><a href="/api/dealer/export.csv" className="dealer-export"><Download/> خروجی CSV</a></div></header><div className="wrap dealer-content">
  {tab==='overview'&&<><section className="dealer-welcome"><div><span>داشبورد نمایشگاه حرفه‌ای</span><h1>موجودی، مشتری و پیگیری فروش را یکجا مدیریت کن.</h1><p>قیمت خرید، قیمت هدف، فروش واقعی، مشتری‌های داغ و تماس‌های عقب‌افتاده را کنار تحلیل بازار ببین.</p></div><div><button onClick={()=>{setTab('inventory');setInventoryForm({...inventoryBlank})}}><Plus/> ثبت خودرو</button><button onClick={()=>{setTab('leads');setLeadForm({...leadBlank})}}><UserRound/> ثبت مشتری</button></div></section><Kpis metrics={metrics}/><div className="dealer-overview-grid"><section><header><h2>آخرین خودروهای موجودی</h2><button onClick={()=>setTab('inventory')}>همه موجودی <ArrowLeft/></button></header><InventoryTable items={(data.inventory||[]).slice(0,5)} edit={setInventoryForm} remove={id=>remove('inventory',id)}/></section><section><header><h2>قیف مشتریان</h2><button onClick={()=>setTab('leads')}>همه مشتریان <ArrowLeft/></button></header><Pipeline leads={data.leads||[]}/></section></div><FollowupPreview items={followups.slice(0,5)} open={()=>setTab('followups')} quickContact={quickContact}/><MarketReport market={data.market}/></>}
  {tab==='inventory'&&<section className="dealer-module"><header><div><span>مدیریت موجودی</span><h1>خودروهای نمایشگاه</h1><p>قیمت تمام‌شده، هدف فروش، فروش واقعی و سود هر خودرو را ثبت کن.</p></div><button className="primary" onClick={()=>setInventoryForm({...inventoryBlank})}><Plus/> افزودن خودرو</button></header><InventoryTable items={data.inventory||[]} edit={setInventoryForm} remove={id=>remove('inventory',id)}/></section>}
  {tab==='leads'&&<section className="dealer-module"><header><div><span>مدیریت ارتباط مشتری</span><h1>مشتریان و سرنخ‌های فروش</h1><p>نیاز، بودجه، اولویت، منبع جذب، خودروی لینک‌شده و پیگیری بعدی هر مشتری را دنبال کن.</p></div><button className="primary" onClick={()=>setLeadForm({...leadBlank})}><Plus/> افزودن مشتری</button></header><LeadTable items={data.leads||[]} edit={setLeadForm} remove={id=>remove('leads',id)} quickContact={quickContact}/></section>}
  {tab==='followups'&&<section className="dealer-module"><header><div><span>برنامه تماس</span><h1>پیگیری‌های فروش</h1><p>مشتری‌هایی که امروز یا قبل‌تر باید پیگیری شوند را سریع تماس‌خورده کن.</p></div><button className="primary" onClick={()=>setLeadForm({...leadBlank,next_follow_at:toInputDateTime(new Date())})}><Plus/> پیگیری جدید</button></header><FollowupTable items={followups} edit={setLeadForm} quickContact={quickContact}/></section>}
 </div>{inventoryForm&&<InventoryModal value={inventoryForm} setValue={setInventoryForm} save={saveInventory} close={()=>setInventoryForm(null)}/>} {leadForm&&<LeadModal value={leadForm} setValue={setLeadForm} save={saveLead} close={()=>setLeadForm(null)} inventory={data?.inventory||[]}/>}</main>
}

function Kpis({metrics}){return <section className="dealer-kpis"><article><Car/><span><small>کل موجودی</small><b>{n(metrics.inventoryCount)}</b></span></article><article><Target/><span><small>آماده / رزرو</small><b>{n(metrics.available)} / {n(metrics.reserved)}</b></span></article><article><Users/><span><small>مشتری فعال / داغ</small><b>{n(metrics.activeLeads)} / {n(metrics.hotLeads)}</b></span></article><article><RefreshCw/><span><small>پیگیری امروز/عقب‌افتاده</small><b>{n(metrics.followupsDue)} / {n(metrics.overdueFollowups)}</b></span></article><article><WalletCards/><span><small>سرمایه موجودی</small><b>{money(metrics.investment)}</b></span></article><article className="profit"><TrendingUp/><span><small>سود هدف موجودی</small><b>{money(metrics.expectedProfit)}</b></span></article><article><TrendingUp/><span><small>سود فروش قطعی</small><b>{money(metrics.realizedProfit)}</b></span></article><article><WalletCards/><span><small>ارزش قیف مشتری</small><b>{money(metrics.leadPipelineValue)}</b></span></article><article><BarChart3/><span><small>نرخ تبدیل</small><b>{n(metrics.conversionRate)}٪</b></span></article><article><TrendingUp/><span><small>ارزش بازار موجودی</small><b>{metrics.marketValue?money(metrics.marketValue):'—'}</b>{metrics.marketVsAsking!==null&&metrics.marketVsAsking!==undefined&&<i className={metrics.marketVsAsking<0?'down':'up'}>{metrics.marketVsAsking>0?'+':''}{n(metrics.marketVsAsking)}٪ نسبت به قیمت هدف</i>}</span></article>{metrics.staleCount>0&&<article className="dealer-warning"><RefreshCw/><span><small>سرمایهٔ خوابیده</small><b>{money(metrics.stalledCapital)}</b><i>{n(metrics.staleCount)} خودرو بیش از ۴۵ روز</i></span></article>}{metrics.overpricedCount>0&&<article className="dealer-warning"><Target/><span><small>گران‌تر از بازار</small><b>{n(metrics.overpricedCount)} خودرو</b><i>احتمال ماندن در نمایشگاه</i></span></article>}</section>}
function Pipeline({leads}){return <div className="lead-funnel">{Object.entries(leadStatus).map(([id,label])=><div key={id}><span>{label}</span><b>{n(leads.filter(item=>item.status===id).length)}</b></div>)}</div>}
function MarketReport({market}){return <section className="dealer-market-report"><header><div><span>گزارش روزانه بازار</span><h2>تصویر امروز خودروتو</h2></div><a href="/cars">مشاهده بازار <ArrowLeft/></a></header><div><article><small>آگهی بررسی‌شده امروز</small><b>{n(market?.analyzedToday)}</b></article><article><small>کل آگهی آرشیو</small><b>{n(market?.totalListings)}</b></article><article><small>فرصت طلایی فعال</small><b>{n(market?.goldenOpportunities)}</b></article></div></section>}
function PriceVerdict({item}){if(!item.market)return <span className="dealer-verdict unknown">بازار نامشخص</span>;const gap=item.askGap,tone=gap===null?'unknown':gap>15?'bad':gap>8?'warn':gap<-8?'under':'good';return <span className={`dealer-verdict ${tone}`} title={item.verdict}>{gap===null?'—':`${gap>0?'+':''}${n(gap)}٪`}{item.suggestedPrice?<small>پیشنهاد: {money(item.suggestedPrice)}</small>:null}</span>}
function ProfitCell({item}){const targetProfit=(Number(item.target_price)||0)-(Number(item.buy_price)||0),actual=item.actualProfit??((item.status==='sold'&&item.sale_price)?Number(item.sale_price)-Number(item.buy_price||0):null);return <span className={(actual??targetProfit)>=0?'dealer-profit up':'dealer-profit down'}>{actual!==null&&actual!==undefined?money(actual):money(targetProfit)}<small>{actual!==null&&actual!==undefined?'قطعی':'هدف'}</small></span>}
function InventoryTable({items,edit,remove}){return <div className="dealer-table-wrap"><table><thead><tr><th>خودرو</th><th>مدل</th><th>خرید</th><th>هدف</th><th>فروش</th><th>سود</th><th>بازار</th><th>وضعیت قیمت</th><th>ماندگاری</th><th>مشتری</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>{items.length?items.map(item=><tr key={item.id}><td><b>{item.title}</b><small>{item.brand} {item.model}</small></td><td>{n(item.year)}</td><td>{money(item.buy_price)}</td><td>{money(item.target_price)}</td><td>{item.sale_price?money(item.sale_price):'—'}{item.sold_at&&<small>{date(item.sold_at)}</small>}</td><td><ProfitCell item={item}/></td><td>{item.market?money(item.market):'—'}</td><td><PriceVerdict item={item}/></td><td><span className={item.stale?'dealer-age stale':'dealer-age'}>{item.daysInStock===null?'—':`${n(item.daysInStock)} روز`}{item.marketDrift!==null&&item.marketDrift!==undefined?<small className={item.marketDrift<0?'down':'up'}>بازار {item.marketDrift>0?'+':''}{n(item.marketDrift)}٪</small>:null}</span></td><td>{item.activeLeads>0?<span className="dealer-leadcount" title={(item.leads||[]).map(lead=>`${lead.name} ${lead.phone||''}`).join(' · ')}>{n(item.activeLeads)} منتظر</span>:<span className="dealer-leadcount empty">—</span>}</td><td><span className={`dealer-status ${item.status}`}>{inventoryStatus[item.status]}</span></td><td><div className="dealer-row-actions"><button onClick={()=>edit({...item,sold_at:toInputDateTime(item.sold_at)})}>ویرایش</button><button onClick={()=>remove(item.id)}><Trash2/></button></div></td></tr>):<tr><td colSpan="12" className="dealer-empty">هنوز خودرویی ثبت نشده است.</td></tr>}</tbody></table></div>}
function LeadTable({items,edit,remove,quickContact}){return <div className="dealer-table-wrap"><table><thead><tr><th>مشتری</th><th>اولویت</th><th>خودروی درخواستی</th><th>لینک موجودی</th><th>بودجه</th><th>مرحله</th><th>پیگیری بعدی</th><th>یادداشت</th><th>عملیات</th></tr></thead><tbody>{items.length?items.map(item=><tr key={item.id}><td><b>{item.name}</b><small>{item.phone||'بدون شماره'} · {item.source||'منبع نامشخص'}</small></td><td><span className={`lead-priority ${item.priority||'normal'}`}>{leadPriority[item.priority]||leadPriority.normal}</span></td><td>{item.vehicle||'—'}</td><td>{item.inventory_title?<span className="dealer-chip">{item.inventory_title}</span>:'—'}</td><td>{money(item.budget)}</td><td><span className={`dealer-status ${item.status}`}>{leadStatus[item.status]}</span></td><td><FollowupBadge item={item}/></td><td>{item.notes||'—'}</td><td><div className="dealer-row-actions"><button onClick={()=>quickContact(item)}>تماس شد</button><button onClick={()=>edit({...item,next_follow_at:toInputDateTime(item.next_follow_at),last_contact_at:toInputDateTime(item.last_contact_at)})}>ویرایش</button><button onClick={()=>remove(item.id)}><Trash2/></button></div></td></tr>):<tr><td colSpan="9" className="dealer-empty">هنوز مشتری‌ای ثبت نشده است.</td></tr>}</tbody></table></div>}
function FollowupBadge({item}){if(!item.next_follow_at)return <span className="dealer-chip muted">بدون برنامه</span>;return <span className={item.followupOverdue?'dealer-chip danger':item.followupToday?'dealer-chip warn':'dealer-chip'}>{date(item.next_follow_at)}{item.last_contact_at&&<small>آخرین تماس: {date(item.last_contact_at)}</small>}</span>}
function FollowupPreview({items,open,quickContact}){return <section className="dealer-followup-panel"><header><div><span>پیگیری‌های نزدیک</span><h2>تماس‌هایی که نباید عقب بیفتد</h2></div><button onClick={open}>همه پیگیری‌ها <ArrowLeft/></button></header>{items.length?<div className="dealer-followup-list">{items.map(item=><article className={item.followupOverdue?'overdue':''} key={item.id}><div><b>{item.name}</b><span>{item.vehicle||item.inventory_title||'بدون خودرو'} · {date(item.next_follow_at)}</span></div><button onClick={()=>quickContact(item)}>ثبت تماس</button></article>)}</div>:<p className="dealer-empty-note">فعلاً پیگیری زمان‌دار نداری.</p>}</section>}
function FollowupTable({items,edit,quickContact}){return <div className="dealer-followup-list full">{items.length?items.map(item=><article className={item.followupOverdue?'overdue':item.followupToday?'today':''} key={item.id}><div><b>{item.name}</b><span>{item.phone||'بدون شماره'} · {item.vehicle||item.inventory_title||'بدون خودرو'} · {date(item.next_follow_at)}</span><small>{item.notes||'بدون یادداشت'}</small></div><div><span className={`lead-priority ${item.priority||'normal'}`}>{leadPriority[item.priority]||leadPriority.normal}</span><button onClick={()=>quickContact(item)}>تماس شد</button><button onClick={()=>edit({...item,next_follow_at:toInputDateTime(item.next_follow_at),last_contact_at:toInputDateTime(item.last_contact_at)})}>ویرایش</button></div></article>):<p className="dealer-empty-note">هنوز برنامه پیگیری ثبت نشده است.</p>}</div>}
function Modal({title,children,save,close}){return <div className="dealer-modal-backdrop"><form className="dealer-modal" onSubmit={save}><header><h2>{title}</h2><button type="button" onClick={close}><X/></button></header>{children}<footer><button type="button" className="secondary" onClick={close}>انصراف</button><button className="primary">ذخیره اطلاعات</button></footer></form></div>}
function InventoryModal({value,setValue,save,close}){return <Modal title={value.id?'ویرایش خودرو':'ثبت خودرو در موجودی'} save={save} close={close}><div className="dealer-fields"><label className="wide">عنوان خودرو<input required value={value.title||''} onChange={field(value,setValue,'title')} placeholder="مثلاً تارا اتوماتیک V4"/></label><label>برند<input value={value.brand||''} onChange={field(value,setValue,'brand')}/></label><label>مدل<input value={value.model||''} onChange={field(value,setValue,'model')}/></label><label>سال ساخت<input inputMode="numeric" value={value.year||''} onChange={field(value,setValue,'year')}/></label><label>وضعیت<select value={value.status||'available'} onChange={field(value,setValue,'status')}>{Object.entries(inventoryStatus).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>قیمت خرید<input inputMode="numeric" value={value.buy_price||''} onChange={field(value,setValue,'buy_price')}/></label><label>قیمت هدف فروش<input inputMode="numeric" value={value.target_price||''} onChange={field(value,setValue,'target_price')}/></label><label>قیمت فروش واقعی<input inputMode="numeric" value={value.sale_price||''} onChange={field(value,setValue,'sale_price')}/></label><label>تاریخ فروش<input type="datetime-local" value={toInputDateTime(value.sold_at)} onChange={field(value,setValue,'sold_at')}/></label><label className="wide">یادداشت<textarea value={value.notes||''} onChange={field(value,setValue,'notes')}/></label></div></Modal>}
function LeadModal({value,setValue,save,close,inventory=[]}){return <Modal title={value.id?'ویرایش مشتری':'ثبت مشتری جدید'} save={save} close={close}><div className="dealer-fields"><label>نام مشتری<input required value={value.name||''} onChange={field(value,setValue,'name')}/></label><label>شماره تماس<input dir="ltr" value={value.phone||''} onChange={field(value,setValue,'phone')}/></label><label>اولویت<select value={value.priority||'normal'} onChange={field(value,setValue,'priority')}>{Object.entries(leadPriority).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>منبع جذب<input value={value.source||''} onChange={field(value,setValue,'source')} placeholder="دیوار، اینستاگرام، معرفی..."/></label><label className="wide">خودروی موردنظر<input value={value.vehicle||''} onChange={field(value,setValue,'vehicle')}/></label><label className="wide">کدام خودروی موجودی؟<select value={value.inventory_id||''} onChange={event=>setValue({...value,inventory_id:event.target.value})}><option value="">وصل نشده</option>{inventory.map(item=><option value={item.id} key={item.id}>{item.title} — {n(item.year)}</option>)}</select><small>با وصل‌کردن مشتری به خودرو، در جدول موجودی می‌بینی چه کسی منتظر کدام ماشین است.</small></label><label>بودجه<input inputMode="numeric" value={value.budget||''} onChange={field(value,setValue,'budget')}/></label><label>مرحله فروش<select value={value.status||'new'} onChange={field(value,setValue,'status')}>{Object.entries(leadStatus).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>پیگیری بعدی<input type="datetime-local" value={toInputDateTime(value.next_follow_at)} onChange={field(value,setValue,'next_follow_at')}/></label><label>آخرین تماس<input type="datetime-local" value={toInputDateTime(value.last_contact_at)} onChange={field(value,setValue,'last_contact_at')}/></label><label className="wide">یادداشت پیگیری<textarea value={value.notes||''} onChange={field(value,setValue,'notes')}/></label></div></Modal>}
